from pathlib import Path

RR = Path(r"D:\codeguard-ai-stage3\artifacts\codeguard-ai\backend\app\services\report_renderer")

# ========== 1. content.py — ensure HTML unescape is present ==========
p = RR / "content.py"
s = p.read_text(encoding="utf-8")
if "html.unescape" not in s:
    s = s.replace("import ast\nimport json\nimport re",
                  "import ast\nimport html\nimport json\nimport re", 1)
    old = 's = CONFLICT_RE.sub("", str(v))\n    s = _strip_markdown(s)'
    new = 's = CONFLICT_RE.sub("", str(v))\n    s = html.unescape(html.unescape(html.unescape(s)))\n    s = _strip_markdown(s)'
    if old in s:
        s = s.replace(old, new, 1)
        print("content.py: unescape added")
    else:
        print("content.py: _clean pattern not found")
else:
    print("content.py: already has unescape")
p.write_text(s, encoding="utf-8", newline="\n")

# ========== 2. api.py — fix special-title matching ==========
p = RR / "api.py"
s = p.read_text(encoding="utf-8").lstrip("\ufeff")

old_match = '''        if lower == "acknowledgement":
            ack = section
        elif lower == "references":
            refs = section
        elif lower == "abstract":
            abstract = section
        else:
            chapters.append(section)'''
new_match = '''        # Normalize title for matching
        norm = lower.strip().rstrip(":").rstrip(".")
        ack_names = {"acknowledgement", "acknowledgements",
                     "acknowledgment", "acknowledgments"}
        refs_names = {"references", "reference", "bibliography"}
        abs_names = {"abstract", "summary"}
        skip_names = {"appendices", "appendix", "table of contents", "contents"}

        if norm in ack_names:
            ack = section
        elif norm in refs_names:
            refs = section
        elif norm in abs_names:
            abstract = section
        elif norm in skip_names:
            # Skip — these are auto-generated by back_matter template
            pass
        else:
            chapters.append(section)'''
if old_match in s:
    s = s.replace(old_match, new_match, 1)
    print("api.py: title matching fixed")
else:
    print("api.py: title match pattern NOT found")

p.write_text(s, encoding="utf-8", newline="\n")

# ========== 3. pdf_structure.py — dedupe similar titles ==========
p = RR / "pdf_structure.py"
s = p.read_text(encoding="utf-8")
if "def _dedupe_titles" not in s:
    helper = '''

def _dedupe_titles(headings):
    """Remove duplicate/similar titles (e.g. 'Appendices' twice)."""
    import re as _re
    seen_keys = set()
    out = []
    for h in headings:
        t = h.get("title", "").strip()
        # Normalize: strip leading number, lowercase, strip punctuation
        norm = _re.sub(r"^\\d+(?:\\.\\d+)*\\.?\\s*", "", t).strip().lower()
        norm = _re.sub(r"[^a-z0-9]+", "", norm)
        # Treat "appendix"/"appendices" as same
        if norm in ("appendix", "appendices"):
            norm = "appendix"
        if norm in ("references", "reference", "bibliography"):
            norm = "references"
        if norm in seen_keys:
            continue
        seen_keys.add(norm)
        out.append(h)
    return out
'''
    # Insert helper before "def extract_structure"
    s = s.replace("def extract_structure(pdf_bytes):",
                  helper.lstrip() + "\n\ndef extract_structure(pdf_bytes):", 1)
    # Apply dedupe before final return
    s = s.replace("    output.sort(key=lambda c: (c[\"page\"], c[\"depth\"]))\n    return output[:40]",
                  "    output.sort(key=lambda c: (c[\"page\"], c[\"depth\"]))\n    output = _dedupe_titles(output)\n    return output[:40]",
                  1)
    print("pdf_structure.py: dedupe added")
else:
    print("pdf_structure.py: already has dedupe")

p.write_text(s, encoding="utf-8", newline="\n")

# ========== 4. toc.html.j2 — re-add Acknowledgement + Abstract entries ==========
p = RR / "templates" / "toc.html.j2"
s = p.read_text(encoding="utf-8")
if "Acknowledgement" not in s:
    new_toc = '''<section class="page front" id="anchor-toc">
  <h1>Table of Contents</h1>
  <div class="rule"></div>

  <ul class="toc-list">
    <li><span class="toc-title">Acknowledgement</span></li>
    <li><span class="toc-title">Abstract</span></li>

    {% for ch in ctx.chapters %}
    <li><span class="toc-title">{{ ch.heading }}</span></li>
    {% endfor %}

    <li><span class="toc-title">{{ ctx.chapters|length + 1 }}. Appendices</span></li>
    <li><span class="toc-title">{{ ctx.chapters|length + 2 }}. References</span></li>
  </ul>
</section>
'''
    p.write_text(new_toc, encoding="utf-8", newline="\n")
    print("toc.html.j2: Acknowledgement + Abstract entries added")
else:
    print("toc.html.j2: already has Acknowledgement")

print("ALL DONE")