import { useEffect, useRef, useState } from "react";
import {
  AlertCircle,
  Download,
  FileText,
  LoaderCircle,
  RefreshCw,
} from "lucide-react";

import {
  useGenerateReport,
  useGetReport,
  useGetReportInputs,
  useRegenerateReportSection,
  getGetReportQueryKey,
  getGetReportInputsQueryKey,
  type ReportSection,
} from "@workspace/api-client-react";

type ErrorLike = { detail?: string } | string | null | undefined;

const messageFrom = (error: unknown, fallback: string) => {
  const data = (error as { data?: ErrorLike })?.data;

  if (typeof data === "string" && data.trim()) return data;

  if (
    data &&
    typeof data === "object" &&
    typeof data.detail === "string"
  ) {
    return data.detail;
  }

  return fallback;
};

export default function ReportStudio({
  projectId,
}: {
  projectId: string | null;
}) {
  const [sections, setSections] = useState<ReportSection[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [regeneratingId, setRegeneratingId] = useState<string | null>(null);

  const reportQuery = useGetReport(projectId ?? "", {
    query: {
      enabled: Boolean(projectId),
      queryKey: getGetReportQueryKey(projectId ?? ""),
    },
  });

  const reportInputs = useGetReportInputs(projectId ?? "", {
    query: {
      enabled: Boolean(projectId),
      queryKey: getGetReportInputsQueryKey(projectId ?? ""),
    },
  });

  const generateReport = useGenerateReport();
  const regenerateSection = useRegenerateReportSection();
  const autoGeneratedForProject = useRef<string | null>(null);

  const runGenerate = () => {
    if (!projectId) return;
    setError(null);
    generateReport.mutate(
      { projectId },
      {
        onSuccess: (report) =>
          setSections([...report.sections].sort((a, b) => a.order - b.order)),
        onError: (mutationError) =>
          setError(messageFrom(mutationError, "The report could not be generated. Try again.")),
      },
    );
  };

  useEffect(() => {
    const loaded = reportQuery.data?.sections;

    if (loaded?.length) {
      setSections(
        [...loaded].sort((a, b) => a.order - b.order),
      );
    }
  }, [reportQuery.data]);

  useEffect(() => {
    if (
      projectId &&
      reportInputs.data?.sample_report.uploaded &&
      reportQuery.data?.status !== "generated" &&
      !generateReport.isPending &&
      autoGeneratedForProject.current !== projectId
    ) {
      autoGeneratedForProject.current = projectId;
      runGenerate();
    }
  }, [projectId, reportInputs.data, reportQuery.data?.status, generateReport.isPending]);

  if (!projectId) return null;

  const isGenerating = generateReport.isPending;

  const runRegenerate = (section: ReportSection) => {
    setError(null);
    setRegeneratingId(section.id);

    regenerateSection.mutate(
      {
        projectId,
        sectionId: section.id,
        data: {
          content: section.content,
        },
      },
      {
        onSuccess: (updated) =>
          setSections((current) =>
            current.map((item) =>
              item.id === updated.id ? updated : item,
            ),
          ),

        onError: (mutationError) =>
          setError(
            messageFrom(
              mutationError,
              "That section could not be regenerated. Try again.",
            ),
          ),

        onSettled: () => setRegeneratingId(null),
      },
    );
  };

  const updateContent = (
    sectionId: string,
    content: string,
  ) => {
    setSections((current) =>
      current.map((item) =>
        item.id === sectionId
          ? { ...item, content }
          : item,
      ),
    );
  };

  return (
    <section
      className="mt-6 overflow-hidden rounded-[1.5rem] border border-[#dbe4dc] bg-[#fbfcf7] shadow-[0_12px_38px_rgba(24,59,64,.06)]"
      data-testid="section-report-studio"
    >
      <div className="border-b border-[#e1e8df] bg-[#f4f8f1] px-5 py-5 sm:px-7">
        <div>
          <div>
            <div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-[#4d907e]">
              <FileText size={13} />
              Stage 3 · report
            </div>

            <h2 className="cg-display text-2xl font-semibold tracking-[-0.045em] text-[#183f43]">
              Write the report from what is actually there.
            </h2>

            <p className="mt-2 max-w-2xl text-sm leading-6 text-[#687871]">
              Sections are written from your analyzed project and
              the uploaded sample report's structure. Anything missing is marked{" "}
              <span className="font-bold">Not detected</span> or{" "}
              <span className="font-bold">Not provided</span>{" "}
              instead of being invented.
            </p>
          </div>

        </div>
      </div>

      <div className="px-5 py-5 sm:px-7 sm:py-6">
        {error && (
          <div
            className="mb-5 flex items-start gap-2.5 rounded-lg border border-[#efc6ba] bg-[#fff4f0] p-3 text-xs text-[#934a39]"
            data-testid="error-report-generation"
          >
            <AlertCircle
              className="mt-0.5 shrink-0"
              size={15}
            />
            <span>{error}</span>
          </div>
        )}

        {isGenerating && (
          <div
            className="space-y-3"
            data-testid="loading-report"
          >
            <p className="flex items-center gap-2 text-xs font-semibold text-[#4d7f72]">
              <LoaderCircle
                size={13}
                className="animate-spin"
              />
              Writing your report section by section…
            </p>

            {[0, 1, 2].map((index) => (
              <div
                key={index}
                className="cg-shimmer h-28 rounded-xl"
              />
            ))}
          </div>
        )}

        {!isGenerating && !sections.length && (
          <div
            className="flex min-h-32 items-center justify-center rounded-xl border border-dashed border-[#cbd4ca] px-6 text-center text-xs text-[#8b958d]"
            data-testid="empty-report"
          >
            Upload a sample report to start automatic generation.
          </div>
        )}

        {!isGenerating && sections.length > 0 && (
          <div>
            <div className="mb-4 flex items-center justify-between gap-3">
              <p className="text-xs font-semibold text-[#58766e]">
                Report ready as editable text and PDF.
              </p>
              <a
                href={`/api/project/${projectId}/report.pdf`}
                download="project-report.pdf"
                className="inline-flex shrink-0 items-center gap-2 rounded-lg bg-[#216e65] px-3 py-2 text-xs font-bold text-white transition-colors hover:bg-[#185b54]"
                data-testid="button-download-report-pdf"
              >
                <Download size={14} />
                Download PDF
              </a>
            </div>
            <div
              className="space-y-4"
              data-testid="list-report-sections"
            >
            {sections.map((section) => (
              <article
                key={section.id}
                className="rounded-xl border border-[#e3e7de] bg-[#f8faf4] p-4"
                data-testid={`section-report-${section.id}`}
              >
                <div className="mb-3 flex items-center justify-between gap-3">
                  <h3 className="text-sm font-bold text-[#264b4c]">
                    {section.title}
                  </h3>

                  <button
                    type="button"
                    onClick={() => runRegenerate(section)}
                    disabled={
                      regeneratingId === section.id
                    }
                    className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-[#d4ddd3] bg-[#f2f7f1] px-3 py-1.5 text-[11px] font-bold text-[#42635e] transition-colors hover:bg-[#e8f2e9] disabled:cursor-not-allowed disabled:opacity-50"
                    data-testid={`button-regenerate-${section.id}`}
                  >
                    <RefreshCw
                      size={13}
                      className={
                        regeneratingId === section.id
                          ? "animate-spin"
                          : ""
                      }
                    />

                    {regeneratingId === section.id
                      ? "Rewriting…"
                      : "Regenerate"}
                  </button>
                </div>

                <textarea
                  value={section.content}
                  onChange={(event) =>
                    updateContent(
                      section.id,
                      event.target.value,
                    )
                  }
                  rows={Math.min(
                    18,
                    Math.max(
                      6,
                      Math.ceil(
                        section.content.length / 90,
                      ),
                    ),
                  )}
                  className="w-full resize-y rounded-lg border border-[#dde4da] bg-white p-3 text-sm leading-6 text-[#3f5b57] outline-none focus:border-[#8dc0ae]"
                  data-testid={`textarea-report-${section.id}`}
                />
              </article>
            ))}
            </div>
          </div>
        )}
      </div>
    </section>
  );
}